version: '3'
services:
  bookstore:
    build: .
    depends_on:
      - db
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - BOOKSTORE_MONGO_URL=mongodb://db:27017/bookstore
  db:
    image: "mongo"
